services:

  loki:
    image: grafana/loki:3.0.0
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml
      - loki-data:/loki
    command: -config.file=/etc/loki/config.yml
    networks:
      - logging
    labels:
      app: "loki"
      lab: "lab07"

    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  promtail:
    image: grafana/promtail:3.0.0
    ports:
      - "9080:9080"
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/snap/docker/common/var-lib-docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - logging
    labels:
      logging: "promtail"
      app: "promtail"
      lab: "lab07"

  grafana:
    image: grafana/grafana:12.3.1
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - logging
    labels:
      app: "grafana"
      lab: "lab07"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app-python:
    build:
      context: ../app_python
    container_name: devops-python
    ports:
      - "8000:5000"
    networks:
      - logging
    labels:
      lab: "lab07"
      app: "devops-python"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

volumes:
  loki-data:
  grafana-data:

networks:
  logging:
