apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info-service
  labels:
    app: devops-info
spec:
  replicas: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: devops-info

  template:
    metadata:
      labels:
        app: devops-info

    spec:
      containers:
        - name: devops-info-container
          image: din19pg/python-service:latest

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"
            - name: DEBUG
              value: "true"

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3
