{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "devops-info.fullname" .)) .Values.secret.name }}
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secret.data.username | quote }}
  password: {{ .Values.secret.data.password | quote }}
{{- end }}
