replicaCount: 1

image:
  repository: din19pg/python-service
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: NodePort
  port: 80
  targetPort: 8000

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
