replicaCount: 1

image:
  repository: din19pg/python-service
  tag: "latest"
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: NodePort
  port: 80
  targetPort: 5000

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5

app:
  environment: dev
  logLevel: DEBUG
  dataDir: /data

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""

secret:
  create: false
  name: devops-info-secret
